version: '3'

services:

# Reverse proxy
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./docker/ngingx-proxy/data:/data
      - ./docker/letsencrypt:/etc/letsencrypt

# Password manager
  bitwarden:
    image: 'vaultwarden/server:latest'
    restart: unless-stopped
    networks:
      - default
    container_name: 'bitwarden'
    volumes:
      - ./docker/vw-data:/data
    depends_on:
      - nginx-proxy

# Local DNS
  pihole:
    image: 'pihole/pihole:latest'
    restart: unless-stopped
    networks:
      - default
    container_name: 'pihole'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      # Used during setup since the raspberry cannot yet point to itself
      - '8080:80/tcp'
    volumes:
      - ./docker/pihole/etc/pihole:/etc/pihole
      - ./docker/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    environment:
      TZ: 'Europe/Rome'
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}" 
    depends_on:
      - nginx-proxy
